/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.mappers.Graph3D;

import static java.lang.Math.*;
import pl.edu.icm.visnow.datasets.RegularField;
/**
 *
 * @author  Krzysztof S. Nowinski, University of Warsaw, ICM
 */
public class GUI extends javax.swing.JPanel
{
   private RegularField inField = null;
   private Params params = new Params();
   
   private Object parentModule = null;
   private float smax;
   /** Creates new form GUI */
   public GUI()
   {
      initComponents();
      dataComponentSelector.setScalarComponentsOnly(true);
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      scaleSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
      fieldZBox = new javax.swing.JCheckBox();
      jPanel1 = new javax.swing.JPanel();
      dataComponentSelector = new pl.edu.icm.visnow.lib.gui.DataComponentSelector();

      setMinimumSize(new java.awt.Dimension(150, 580));
      setPreferredSize(new java.awt.Dimension(200, 600));
      setLayout(new java.awt.GridBagLayout());

      scaleSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("graph scale"));
      scaleSlider.setMinimumSize(new java.awt.Dimension(180, 60));
      scaleSlider.setPreferredSize(new java.awt.Dimension(200, 65));
      scaleSlider.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            scaleSliderStateChanged(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weightx = 1.0;
      add(scaleSlider, gridBagConstraints);

      fieldZBox.setText(" set z-coordinate to field range");
      fieldZBox.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            fieldZBoxActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
      add(fieldZBox, gridBagConstraints);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weighty = 1.0;
      add(jPanel1, gridBagConstraints);

      dataComponentSelector.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            dataComponentSelectorStateChanged(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      add(dataComponentSelector, gridBagConstraints);
   }// </editor-fold>//GEN-END:initComponents


   private void scaleSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scaleSliderStateChanged
      params.setAdjusting(scaleSlider.isAdjusting());
      params.setScale(scaleSlider.getVal());
      params.fireStateChanged();
   }//GEN-LAST:event_scaleSliderStateChanged

private void fieldZBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZBoxActionPerformed
      params.setZFromData(fieldZBox.isSelected());
      params.fireStateChanged();
}//GEN-LAST:event_fieldZBoxActionPerformed

private void dataComponentSelectorStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_dataComponentSelectorStateChanged
{//GEN-HEADEREND:event_dataComponentSelectorStateChanged
    params.setComponent(dataComponentSelector.getComponent());
    setScaleMinMax();
    params.fireStateChanged();
}//GEN-LAST:event_dataComponentSelectorStateChanged
   
   public void setInField(RegularField inField)
   {
      params.setActive(false);
      if (inField.getDims()==null || inField.getDims().length!=2)
          return;
      this.inField = inField;
      dataComponentSelector.setDataSchema(inField.getSchema());
      params.setComponent(0);
      setScaleMinMax();    
      params.setActive(true);
   }
   
   private void setScaleMinMax()
   {
      float min = inField.getData(params.getComponent()).getMinv();
      float max = inField.getData(params.getComponent()).getMaxv();
      if (max <= min)
         max = min + .001f;
      float ext = inField.getExtents()[1][0] - inField.getExtents()[0][0];
      for (int i = 1; i < inField.getNSpace(); i++)
         ext = max(ext,inField.getExtents()[1][i] - inField.getExtents()[0][i]);
      int k = (int)round(log10(ext / (max - min)) - .9);
      smax = (float)pow(10.,k+1);
      scaleSlider.setMin(-smax);
      scaleSlider.setMax(smax);
      scaleSlider.setVal(0.4f * smax);
      params.setScale(scaleSlider.getVal());
   }

    public void setParams(Params params)
    {
        this.params = params;
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private pl.edu.icm.visnow.lib.gui.DataComponentSelector dataComponentSelector;
   private javax.swing.JCheckBox fieldZBox;
   private javax.swing.JPanel jPanel1;
   private pl.edu.icm.visnow.gui.widgets.FloatSlider scaleSlider;
   // End of variables declaration//GEN-END:variables
   
}
