/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.readers.ReadOBJ;

/*
 * GUI.java
 *
 * Created on 14 czerwiec 2007, 10:51
 */
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import pl.edu.icm.visnow.system.main.VisNow;

public class GUI extends javax.swing.JPanel {

    private Params params = new Params();
    private String lastPath = null;

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        objPathTF = new javax.swing.JTextField();
        browseObjButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(200, 400));
        setPreferredSize(new java.awt.Dimension(200, 400));
        setRequestFocusEnabled(false);
        setLayout(null);

        jLabel1.setText("Read object");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 120, 15);

        objPathTF.setMaximumSize(null);
        objPathTF.setMinimumSize(new java.awt.Dimension(180, 20));
        objPathTF.setPreferredSize(new java.awt.Dimension(180, 20));
        add(objPathTF);
        objPathTF.setBounds(0, 60, 229, 20);

        browseObjButton.setText("Browse...");
        browseObjButton.setMargin(new java.awt.Insets(2, 7, 2, 7));
        browseObjButton.setPreferredSize(new java.awt.Dimension(88, 20));
        browseObjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseObjButtonActionPerformed(evt);
            }
        });
        add(browseObjButton);
        browseObjButton.setBounds(140, 30, 88, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void browseObjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseObjButtonActionPerformed
       JFileChooser fileChooser = new JFileChooser();
       if (lastPath == null)
          fileChooser.setCurrentDirectory(new File(VisNow.get().getMainConfig().getUsableDataPath(ReadOBJ.class)));
       else
          fileChooser.setCurrentDirectory(new File(lastPath));

       FileNameExtensionFilter allObiectFilter = new FileNameExtensionFilter("All object files", "obj", "OBJ");
       fileChooser.addChoosableFileFilter(allObiectFilter);
       int returnVal = fileChooser.showOpenDialog(this);
       if (returnVal == JFileChooser.APPROVE_OPTION)
       {
          String path = fileChooser.getSelectedFile().getAbsolutePath();
          lastPath = path.substring(0, path.lastIndexOf(File.separator));
          VisNow.get().getMainConfig().setLastDataPath(lastPath,ReadOBJ.class);
          objPathTF.setText(path);
          params.setObjPath(path);
       }
    }//GEN-LAST:event_browseObjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseObjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField objPathTF;
    // End of variables declaration//GEN-END:variables

    /**
     * @param params the params to set
     */
    public void setParams(Params params) {
        this.params = params;
    }

    void activateOpenDialog() {
        browseObjButtonActionPerformed(null);
    }
}
