/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.mappers.LineSlice;

public class LineSliceGUI extends javax.swing.JPanel
{
   protected LineSliceParams params = null;
   protected int[] dims =  {1, 1};

   /** Creates new form EmptyVisnowModuleGUI */
   public LineSliceGUI()
   {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        axisGroup = new javax.swing.ButtonGroup();
        xRadioButton = new javax.swing.JRadioButton();
        yRadioButton = new javax.swing.JRadioButton();
        zRadioButton = new javax.swing.JRadioButton();
        dynSlidersBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        xSlider = new pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider();
        ySlider = new pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider();
        zSlider = new pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider();
        jPanel1 = new javax.swing.JPanel();
        recomputeMinMaxCB = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(220, 480));
        setPreferredSize(new java.awt.Dimension(242, 494));
        setLayout(new java.awt.GridBagLayout());

        axisGroup.add(xRadioButton);
        xRadioButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        xRadioButton.setSelected(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/edu/icm/visnow/lib/basic/mappers/LineSlice/Bundle"); // NOI18N
        xRadioButton.setText(bundle.getString("LineSliceGUI.xRadioButton.text_1")); // NOI18N
        xRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadioButtonActionPerformed(evt);
            }
        });
        add(xRadioButton, new java.awt.GridBagConstraints());

        axisGroup.add(yRadioButton);
        yRadioButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        yRadioButton.setText(bundle.getString("LineSliceGUI.yRadioButton.text_1")); // NOI18N
        yRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(yRadioButton, gridBagConstraints);

        axisGroup.add(zRadioButton);
        zRadioButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        zRadioButton.setText(bundle.getString("LineSliceGUI.zRadioButton.text_1")); // NOI18N
        zRadioButton.setEnabled(false);
        zRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zRadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(zRadioButton, gridBagConstraints);

        dynSlidersBox.setText(bundle.getString("LineSliceGUI.dynSlidersBox.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(dynSlidersBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);

        xSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(xSlider, gridBagConstraints);

        ySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ySliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(ySlider, gridBagConstraints);

        zSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(zSlider, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        add(jPanel1, gridBagConstraints);

        recomputeMinMaxCB.setText(bundle.getString("LineSliceGUI.recomputeMinMaxCB.text")); // NOI18N
        recomputeMinMaxCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recomputeMinMaxCBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        add(recomputeMinMaxCB, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void xRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xRadioButtonActionPerformed
    {//GEN-HEADEREND:event_xRadioButtonActionPerformed
       updateAxis();
}//GEN-LAST:event_xRadioButtonActionPerformed

    private void yRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yRadioButtonActionPerformed
    {//GEN-HEADEREND:event_yRadioButtonActionPerformed
       updateAxis();
}//GEN-LAST:event_yRadioButtonActionPerformed

    private void zRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zRadioButtonActionPerformed
    {//GEN-HEADEREND:event_zRadioButtonActionPerformed
       updateAxis();
}//GEN-LAST:event_zRadioButtonActionPerformed

    private void xSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_xSliderStateChanged
    {//GEN-HEADEREND:event_xSliderStateChanged
       if (!xSlider.isAdjusting() || dynSlidersBox.isSelected())
          params.setXCoord(xSlider.getVal()); 
    }//GEN-LAST:event_xSliderStateChanged

    private void ySliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_ySliderStateChanged
    {//GEN-HEADEREND:event_ySliderStateChanged
       if (!ySlider.isAdjusting() || dynSlidersBox.isSelected())
          params.setYCoord(ySlider.getVal());
    }//GEN-LAST:event_ySliderStateChanged

    private void zSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_zSliderStateChanged
    {//GEN-HEADEREND:event_zSliderStateChanged
       if (!zSlider.isAdjusting() || dynSlidersBox.isSelected())
          params.setZCoord(zSlider.getVal()); 
    }//GEN-LAST:event_zSliderStateChanged

    private void recomputeMinMaxCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomputeMinMaxCBActionPerformed
        params.setRecalculateMinMax(recomputeMinMaxCB.isSelected());
    }//GEN-LAST:event_recomputeMinMaxCBActionPerformed

    private void updateAxis()
    {
       xSlider.setEnabled(!xRadioButton.isSelected());
       ySlider.setEnabled(!yRadioButton.isSelected());
       zSlider.setEnabled(!zRadioButton.isSelected() && dims.length > 2);
       if (xRadioButton.isSelected())
          params.setAxis(0);
       else if (yRadioButton.isSelected())
          params.setAxis(1);
       else
          params.setAxis(2);
    }
    
   public void setParams(LineSliceParams params)
   {
      this.params = params;
   }

   public void setDims(int[] dims)
   {
      if (this.dims != null && this.dims.length == dims.length)
      {
         boolean unchanged = true;
         for (int i = 0; i < dims.length; i++)
            unchanged = unchanged && (dims[i] == this.dims[i]);
         if (unchanged)
            return;
      }
      params.setActive(false);
      xSlider.setEnabled(false);
      zSlider.setVisible(dims.length>2);
      zSlider.setEnabled(dims.length>2);
      zRadioButton.setVisible(dims.length>2);
      zRadioButton.setEnabled(dims.length>2);
      ySlider.setVisible(dims.length>1);
      yRadioButton.setVisible(dims.length>1);
      this.dims = dims;
      xRadioButton.setSelected(true);
      xSlider.setMax(dims[0]-1);
      if (xSlider.getVal()>dims[0]-1)
         xSlider.setVal(dims[0]/2);
      ySlider.setMax(dims[1]-1);
      if (ySlider.getVal()>dims[1]-1)
         ySlider.setVal(dims[1]/2);
      if (dims.length>2)
      {
         zSlider.setMax(dims[2]-1);
         if (zSlider.getVal()>dims[2]-1)
            zSlider.setVal(dims[2]/2);
      }
      params.setXCoord(xSlider.getVal());
      params.setYCoord(ySlider.getVal());
      params.setZCoord(zSlider.getVal());
      if (xRadioButton.isSelected())
         params.setAxis(0);
      else if (yRadioButton.isSelected())
         params.setAxis(1);
      else
         params.setAxis(2);
      params.setActive(true);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup axisGroup;
    private javax.swing.JCheckBox dynSlidersBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox recomputeMinMaxCB;
    private javax.swing.JRadioButton xRadioButton;
    private pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider xSlider;
    private javax.swing.JRadioButton yRadioButton;
    private pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider ySlider;
    private javax.swing.JRadioButton zRadioButton;
    private pl.edu.icm.visnow.gui.widgets.EnhancedVerticalIntSlider zSlider;
    // End of variables declaration//GEN-END:variables
}
