/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.application.frames.tabs;

import java.io.File;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import pl.edu.icm.visnow.engine.library.LibraryRoot;
import pl.edu.icm.visnow.engine.library.jar.JarLibReader;
import pl.edu.icm.visnow.engine.library.jar.JarLibraryRoot;
import pl.edu.icm.visnow.engine.commands.LibraryAddCommand;
import pl.edu.icm.visnow.system.framework.VNLibListCellRenderer;
import pl.edu.icm.visnow.system.main.VisNow;

/**
 *
 * @author  Hubert Orlik-Grzesik, University of Warsaw, ICM
 */
public class MRootsPanel extends javax.swing.JPanel
{

   /** Creates new form RootsPanel */
   public MRootsPanel()
   {
      initComponents();
      initList();
   }

   private void initList()
   {
      DefaultListModel model = new DefaultListModel();
      list.setModel(model);
      Vector<LibraryRoot> vector = VisNow.get().getMainLibraries().getLibraries();
      for (LibraryRoot lib : vector)
         model.addElement(lib);
      list.setCellRenderer(new VNLibListCellRenderer());
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newButton = new javax.swing.JButton();
        editorButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        openButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        newButton.setText("New");
        newButton.setEnabled(false);

        editorButton.setText("Editor...");
        editorButton.setEnabled(false);

        setMinimumSize(new java.awt.Dimension(150, 500));
        setPreferredSize(new java.awt.Dimension(160, 600));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Libraries");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jLabel1, gridBagConstraints);

        list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        list.setVisibleRowCount(-1);
        jScrollPane1.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        openButton.setText("Open...");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(openButton, gridBagConstraints);

        addButton.setText("Add to application");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(addButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
   JFileChooser chooser = new JFileChooser()
   {

      @Override
      public boolean accept(File f)
      {
         if (f.isDirectory())
            return true;
         return (f.getName().endsWith(".jar"));
      }
   };
   chooser.setCurrentDirectory(new File(VisNow.get().getMainConfig().getVN2UserFolder()));
   int ret = chooser.showOpenDialog(this);
   if (ret == JFileChooser.APPROVE_OPTION)
   {
      JarLibraryRoot jrl = JarLibReader.readFromJar(chooser.getSelectedFile());

      VisNow.get().getMainLibraries().addLibrary(jrl);
      initList();
      //getPanel().getEnvironment().getApplication().getLibraries().put(chooser.getSelectedFile().getName(),jrl);
      //MutableTreeNode node = this.createNodeFromLibrary(jrl.getRootFolder());
      //libTreeRoot.add(node);
      //getPanel().getLibTree().setModel(new DefaultTreeModel(libTreeRoot));
   }

}//GEN-LAST:event_openButtonActionPerformed

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
   LibraryRoot root = (LibraryRoot) list.getSelectedValue();
   VisNow.get().getMainWindow().getApplicationsPanel().getApplication().getReceiver().receive(
           new LibraryAddCommand(root.getName()));
}//GEN-LAST:event_addButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton editorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    // End of variables declaration//GEN-END:variables
}
