/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.system.framework;

import pl.edu.icm.visnow.application.application.Application;
import pl.edu.icm.visnow.application.frames.ApplicationFrame2;
import pl.edu.icm.visnow.system.main.VisNow;

/**
 *
 * @author Hubert Orlik-Grzesik, University of Warsaw, ICM
 */
public class ApplicationsPanel extends javax.swing.JPanel
{

   //<editor-fold defaultstate="collapsed" desc=" Add/Remove/Get Application ">
   //protected Vector<Application> applications;
   public void addApplication(Application application)
   {
      //applications.add(application);
      ApplicationFrame2 frame = application.getApplicationFrame();
      jTabbedPane.add(frame);
      jTabbedPane.setTitleAt(jTabbedPane.indexOfComponent(frame), frame.getApplication().getTitle());
      jTabbedPane.setSelectedIndex(jTabbedPane.indexOfComponent(frame));
   }

   public void removeCurrentApplication()
   {
      //applications.remove(getApplication());
      VisNow.get().getMainConfig().setWinowXML(getApplication().getApplicationFrame().writeWindowXML());
      //getApplication().getEngine().getModules().clear();
      getApplication().deleteAllModules();
      jTabbedPane.remove(jTabbedPane.getSelectedComponent());
   }

   public Application getApplication()
   {
      if (jTabbedPane.getSelectedComponent() == null)
         return null;
      if (jTabbedPane.getSelectedComponent() instanceof ApplicationFrame2)
         return ((ApplicationFrame2) jTabbedPane.getSelectedComponent()).getApplication();
      return null;
   }

   //public Vector<Application> getApplications() {
   //    return applications;
   //}
   public boolean isApplicationOpened()
   {
      if (getApplication() == null)
         return false;
      return true;
   }

   //</editor-fold>
   /**
    * Creates new form ApplicationsPanel
    */
   public ApplicationsPanel()
   {
      initComponents();
      //applications = new Vector<Application>();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
