/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.filters.GaussianFilter;


import javax.swing.JPanel;

/**
 *
 * @author  Krzysztof S. Nowinski, University of Warsaw, ICM
 */
public class GUI extends JPanel
{
   protected Params params = new Params();
   /** Creates new form InterpolateFieldUI */
   public GUI()
   {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      runButton = new javax.swing.JButton();
      autoToggle = new javax.swing.JToggleButton();
      jLabel2 = new javax.swing.JLabel();
      threadSpinner = new javax.swing.JSpinner();
      jPanel1 = new javax.swing.JPanel();
      sigmaSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
      sigma1Slider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
      bandPassBox = new javax.swing.JCheckBox();
      absBandBox = new javax.swing.JCheckBox();
      highPassBox = new javax.swing.JCheckBox();
      absHighBox = new javax.swing.JCheckBox();

      setBorder(javax.swing.BorderFactory.createEtchedBorder());
      setMinimumSize(new java.awt.Dimension(150, 150));
      setPreferredSize(new java.awt.Dimension(200, 155));
      setLayout(new java.awt.GridBagLayout());

      runButton.setText("run");
      runButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            runButtonActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 6;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 2);
      add(runButton, gridBagConstraints);

      autoToggle.setText("auto");
      autoToggle.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            autoToggleActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 7;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 2);
      add(autoToggle, gridBagConstraints);

      jLabel2.setFont(new java.awt.Font("Dialog", 0, 12));
      jLabel2.setText("threads");
      jLabel2.setMaximumSize(new java.awt.Dimension(45, 15));
      jLabel2.setMinimumSize(new java.awt.Dimension(45, 15));
      jLabel2.setPreferredSize(new java.awt.Dimension(45, 15));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 5;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
      add(jLabel2, gridBagConstraints);

      threadSpinner.setModel(new javax.swing.SpinnerNumberModel(Runtime.getRuntime().availableProcessors(), 1, Runtime.getRuntime().availableProcessors(), 1));
      threadSpinner.setMinimumSize(new java.awt.Dimension(40, 20));
      threadSpinner.setPreferredSize(new java.awt.Dimension(40, 20));
      threadSpinner.setValue(Runtime.getRuntime().availableProcessors());
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 5;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
      add(threadSpinner, gridBagConstraints);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 8;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weighty = 1.0;
      add(jPanel1, gridBagConstraints);

      sigmaSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "sigma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
      sigmaSlider.setMax(30.0F);
      sigmaSlider.setMinimumSize(new java.awt.Dimension(90, 68));
      sigmaSlider.setPreferredSize(new java.awt.Dimension(200, 68));
      sigmaSlider.setVal(10.0F);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      add(sigmaSlider, gridBagConstraints);

      sigma1Slider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "sigma 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
      sigma1Slider.setMax(5.0F);
      sigma1Slider.setMin(0.5F);
      sigma1Slider.setMinimumSize(new java.awt.Dimension(90, 68));
      sigma1Slider.setPreferredSize(new java.awt.Dimension(200, 68));
      sigma1Slider.setVal(1.0F);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      add(sigma1Slider, gridBagConstraints);

      bandPassBox.setFont(new java.awt.Font("Dialog", 0, 12));
      bandPassBox.setText("band pass");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.weightx = 1.0;
      add(bandPassBox, gridBagConstraints);

      absBandBox.setFont(new java.awt.Font("Dialog", 0, 12));
      absBandBox.setText("abs val");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      add(absBandBox, gridBagConstraints);

      highPassBox.setFont(new java.awt.Font("Dialog", 0, 12));
      highPassBox.setText("high pass");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      add(highPassBox, gridBagConstraints);

      absHighBox.setFont(new java.awt.Font("Dialog", 0, 12));
      absHighBox.setText("abs val");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      add(absHighBox, gridBagConstraints);
   }// </editor-fold>//GEN-END:initComponents

   private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
      fireStateChanged();
}//GEN-LAST:event_runButtonActionPerformed

   private void autoToggleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_autoToggleActionPerformed
   {//GEN-HEADEREND:event_autoToggleActionPerformed
      params.setAuto(autoToggle.isSelected());
   }//GEN-LAST:event_autoToggleActionPerformed

   public void setParams(Params params)
   {
      params.setSigma(sigmaSlider.getVal());
      params.setNThreads((Integer)threadSpinner.getValue());
      params.setSigma(sigmaSlider.getVal());
      params.setSigma1(sigma1Slider.getVal());
      params.setHiAbs(absHighBox.isSelected());
      params.setHiPass(highPassBox.isSelected());
      params.setBandPass(bandPassBox.isSelected());
      params.setBandAbs(absBandBox.isSelected());
      this.params = params;
   }
   
   private void fireStateChanged()
   {
      params.setSigma(sigmaSlider.getVal());
      params.setNThreads((Integer)threadSpinner.getValue());
      params.setSigma(sigmaSlider.getVal());
      params.setSigma1(sigma1Slider.getVal());
      params.setHiAbs(absHighBox.isSelected());
      params.setHiPass(highPassBox.isSelected());
      params.setBandPass(bandPassBox.isSelected());
      params.setBandAbs(absBandBox.isSelected());
      params.setActive(true);
   }
   

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JCheckBox absBandBox;
   private javax.swing.JCheckBox absHighBox;
   private javax.swing.JToggleButton autoToggle;
   private javax.swing.JCheckBox bandPassBox;
   private javax.swing.JCheckBox highPassBox;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JButton runButton;
   private pl.edu.icm.visnow.gui.widgets.FloatSlider sigma1Slider;
   private pl.edu.icm.visnow.gui.widgets.FloatSlider sigmaSlider;
   private javax.swing.JSpinner threadSpinner;
   // End of variables declaration//GEN-END:variables
   
}
