/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.Views;

import pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.ViewPanels.ViewPanel;
import java.awt.Dimension;

/**
 * @author  Bartosz Borucki (babor@icm.edu.pl)
 * University of Warsaw, Interdisciplinary Centre
 * for Mathematical and Computational Modelling
 */

public class DoubleViewVertical extends javax.swing.JPanel {
    public static final int VIEWPORT_TOP = 0;
    public static final int VIEWPORT_BOTTOM = 1;

    public static final int NO_CHANGE_DIVIDER_ON_RESIZE = 0;
    public static final int CENTER_DIVIDER_ON_RESIZE = 1;
    private int resizeDividerBehaviour = CENTER_DIVIDER_ON_RESIZE;

    /** Creates new form TwoViewHorizontal */
    public DoubleViewVertical() {
        initComponents();
        splitPane.setDividerLocation(0.5);
    }

    public void reset() {
        setViewPanel(VIEWPORT_TOP, new ViewPanel());
        setViewPanel(VIEWPORT_BOTTOM, new ViewPanel());
    }

    public ViewPanel getViewPanel(int n) {
        switch(n) {
            case VIEWPORT_TOP:
                return getTopViewPanel();
            case VIEWPORT_BOTTOM:
                return getBottomViewPanel();
            default:
                return null;
        }
    }

    public void setViewPanel(int n, ViewPanel panel) {
        int tmp = splitPane.getDividerLocation();
        switch(n) {
            case VIEWPORT_TOP:
                topViewPanel.preRemove();
                splitPane.remove(topViewPanel);
                topViewPanel.setInUse(false);
                topViewPanel = panel;
                splitPane.setTopComponent(topViewPanel);
                topViewPanel.setInUse(true);
                topViewPanel.postAdd();
                break;
            case VIEWPORT_BOTTOM:
                bottomViewPanel.preRemove();
                splitPane.remove(bottomViewPanel);
                bottomViewPanel.setInUse(false);
                bottomViewPanel = panel;
                splitPane.setBottomComponent(bottomViewPanel);
                bottomViewPanel.setInUse(true);
                bottomViewPanel.postAdd();
                break;
        }
        splitPane.setDividerLocation(tmp);
        repaint();
    }


    public ViewPanel getTopViewPanel() {
        return topViewPanel;
    }

    public Dimension getTopViewPanelSize() {
        return topViewPanel.getSize();
    }

    public ViewPanel getBottomViewPanel() {
        return bottomViewPanel;
    }

    public Dimension getBottomViewPanelSize() {
        return bottomViewPanel.getSize();
    }

    public int getDividerLocation() {
        return splitPane.getDividerLocation();
    }

    public void setDividerLocation(int newLocation) {
        splitPane.setDividerLocation(newLocation);
    }

    public void setDividerLocation(double newPercentageLocation) {
        splitPane.setDividerLocation(newPercentageLocation);
    }

    public void centerDivider() {
        setDividerLocation(0.5);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topViewPanel = new pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.ViewPanels.ViewPanel();
        bottomViewPanel = new pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.ViewPanels.ViewPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        splitPane.setDividerLocation(250);
        splitPane.setDividerSize(5);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setTopComponent(topViewPanel);
        splitPane.setRightComponent(bottomViewPanel);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(resizeDividerBehaviour == CENTER_DIVIDER_ON_RESIZE) {
            centerDivider();
        }
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.ViewPanels.ViewPanel bottomViewPanel;
    private javax.swing.JSplitPane splitPane;
    private pl.edu.icm.visnow.lib.basic.viewers.FieldViewer3D.ViewPanels.ViewPanel topViewPanel;
    // End of variables declaration//GEN-END:variables

}
