/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.mappers.ScaleCells;

public class GUI extends javax.swing.JPanel
{

   protected Params params;

   /**
    * Get the value of params
    *
    * @return the value of params
    */
   public Params getParams()
   {
      return params;
   }

   /**
    * Set the value of params
    *
    * @param params new value of params
    */
   public void setParams(Params params)
   {
      this.params = params;
   }

   /** Creates new form EmptyVisnowModuleGUI */
   public GUI()
   {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      scaleSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
      jPanel1 = new javax.swing.JPanel();

      setLayout(new java.awt.BorderLayout());

      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/edu/icm/visnow/lib/basic/mappers/ScaleCells/Bundle"); // NOI18N
      scaleSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("GUI.scaleSlider.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
      scaleSlider.setMinimumSize(new java.awt.Dimension(90, 63));
      scaleSlider.setPreferredSize(new java.awt.Dimension(200, 65));
      scaleSlider.setVal(0.75F);
      scaleSlider.addChangeListener(new javax.swing.event.ChangeListener()
      {
         public void stateChanged(javax.swing.event.ChangeEvent evt)
         {
            scaleSliderStateChanged(evt);
         }
      });
      add(scaleSlider, java.awt.BorderLayout.NORTH);
      add(jPanel1, java.awt.BorderLayout.CENTER);
   }// </editor-fold>//GEN-END:initComponents

   private void scaleSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_scaleSliderStateChanged
   {//GEN-HEADEREND:event_scaleSliderStateChanged
//      if (!scaleSlider.isAdjusting())
      params.setAdjusting(scaleSlider.isAdjusting());
      params.setScale(scaleSlider.getVal());
   }//GEN-LAST:event_scaleSliderStateChanged

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanel1;
   private pl.edu.icm.visnow.gui.widgets.FloatSlider scaleSlider;
   // End of variables declaration//GEN-END:variables
}
