//<editor-fold defaultstate="collapsed" desc=" COPYRIGHT AND LICENSE ">
/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the
University of Warsaw, Interdisciplinary Centre for Mathematical and
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland.

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */
//</editor-fold>

package pl.edu.icm.visnow.lib.gui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import static java.lang.Math.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import pl.edu.icm.visnow.gui.events.FloatValueModificationEvent;
import pl.edu.icm.visnow.gui.events.FloatValueModificationListener;
import pl.edu.icm.visnow.lib.basic.mappers.Isosurface.IsosurfaceGUI;
import pl.edu.icm.visnow.lib.utils.Range;

/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class FloatArrayEditor extends javax.swing.JPanel
{

   private float vMin = 0, vMax = 255;
   private float physMin = 0, physMax = 255;
   private float[] thresholds = null;
   private boolean startSingle = true;
   private int decimals = 2;
   private boolean valuePreferred = true;
   private float rmin = 0, rmax = 100;
   private int maxRangeCount = 10;
   /**
    * Creates new form FloatArrayEditor
    */
   public FloatArrayEditor()
   {
      initComponents();
      JLabel renderer = (JLabel) thresholdList.getCellRenderer();
      renderer.setFont(new Font(Font.DIALOG_INPUT, Font.PLAIN, 9));
      renderer.setHorizontalAlignment(SwingConstants.RIGHT);
      intervalCombo1.addChangeListener(
      new FloatValueModificationListener()
      {
         @Override
         public void floatValueChanged(FloatValueModificationEvent e)
         {
            thresholds = Range.createLinearRange(rmin, rmax, e.getVal());
            setThresholds();
         }
      });
      simplePanel.setVisible(false);
   }

   public void setValuePreferred(boolean valuePreferred)
   {
      this.valuePreferred = valuePreferred;
   }

   public void setPresentation(boolean simple)
   {
       linRangePanel.setVisible(!simple);
       logRangePanel.setVisible(!simple);
       arrayPanel.setVisible(!simple);
       simplePanel.setVisible(simple && !valuePreferred);
       setThrButton.setVisible(!simple);
       addThrButton.setVisible(!simple);
       singleValPanel.setVisible(!simple || valuePreferred);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        simplePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        intervalCombo1 = new pl.edu.icm.visnow.gui.widgets.IntervalCombo();
        singleValPanel = new javax.swing.JPanel();
        thrSlider = new pl.edu.icm.visnow.gui.widgets.FloatSlider();
        setThrButton = new javax.swing.JRadioButton();
        addThrButton = new javax.swing.JRadioButton();
        linRangePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        minLinField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        maxLinField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        intervalCombo = new pl.edu.icm.visnow.gui.widgets.IntervalCombo();
        jPanel1 = new javax.swing.JPanel();
        setLinRangeButton = new javax.swing.JButton();
        addLinRangeButton = new javax.swing.JButton();
        logRangePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        minLogRangeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maxLogRangeField = new javax.swing.JTextField();
        eqSpacedLogRangeToggle = new javax.swing.JCheckBox();
        logValSlider = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        setLogRangeButton = new javax.swing.JButton();
        addLogRangeButton = new javax.swing.JButton();
        arrayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        thresholdList = new javax.swing.JList();
        deleteSelButton = new javax.swing.JButton();
        clearThrButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        simplePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        simplePanel.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setText("interval");
        jLabel8.setName("jLabel8"); // NOI18N
        simplePanel.add(jLabel8, java.awt.BorderLayout.WEST);

        intervalCombo1.setName("intervalCombo1"); // NOI18N
        simplePanel.add(intervalCombo1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(simplePanel, gridBagConstraints);

        singleValPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "single threshold", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        singleValPanel.setName("singleValPanel"); // NOI18N
        singleValPanel.setLayout(new java.awt.GridBagLayout());

        thrSlider.setName("thrSlider"); // NOI18N
        thrSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thrSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        singleValPanel.add(thrSlider, gridBagConstraints);

        buttonGroup1.add(setThrButton);
        setThrButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setThrButton.setSelected(true);
        setThrButton.setText("set");
        setThrButton.setMargin(new java.awt.Insets(0, 2, 0, 2));
        setThrButton.setName("setThrButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        singleValPanel.add(setThrButton, gridBagConstraints);

        buttonGroup1.add(addThrButton);
        addThrButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        addThrButton.setText("add");
        addThrButton.setMargin(new java.awt.Insets(2, 0, 2, 0));
        addThrButton.setName("addThrButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        singleValPanel.add(addThrButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        add(singleValPanel, gridBagConstraints);

        linRangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "linear range", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        linRangePanel.setName("linRangePanel"); // NOI18N
        linRangePanel.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("min");
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        linRangePanel.add(jLabel6, gridBagConstraints);

        minLinField.setText("0");
        minLinField.setMinimumSize(new java.awt.Dimension(60, 20));
        minLinField.setName("minLinField"); // NOI18N
        minLinField.setPreferredSize(new java.awt.Dimension(60, 20));
        minLinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minLinFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        linRangePanel.add(minLinField, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("max");
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        linRangePanel.add(jLabel7, gridBagConstraints);

        maxLinField.setText("100");
        maxLinField.setMinimumSize(new java.awt.Dimension(60, 20));
        maxLinField.setName("maxLinField"); // NOI18N
        maxLinField.setPreferredSize(new java.awt.Dimension(60, 20));
        maxLinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxLinFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        linRangePanel.add(maxLinField, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("interval");
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        linRangePanel.add(jLabel4, gridBagConstraints);

        intervalCombo.setMinimumSize(new java.awt.Dimension(60, 20));
        intervalCombo.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        linRangePanel.add(intervalCombo, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        setLinRangeButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        setLinRangeButton.setText("set");
        setLinRangeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        setLinRangeButton.setName("setLinRangeButton"); // NOI18N
        setLinRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLinRangeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(setLinRangeButton, gridBagConstraints);

        addLinRangeButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addLinRangeButton.setText("add");
        addLinRangeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addLinRangeButton.setName("addLinRangeButton"); // NOI18N
        addLinRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLinRangeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(addLinRangeButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        linRangePanel.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.6;
        add(linRangePanel, gridBagConstraints);

        logRangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "logarithmic range", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        logRangePanel.setInheritsPopupMenu(true);
        logRangePanel.setName("logRangePanel"); // NOI18N
        logRangePanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("min");
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        logRangePanel.add(jLabel2, gridBagConstraints);

        minLogRangeField.setText(".01");
        minLogRangeField.setMinimumSize(new java.awt.Dimension(60, 20));
        minLogRangeField.setName("minLogRangeField"); // NOI18N
        minLogRangeField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        logRangePanel.add(minLogRangeField, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("max");
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        logRangePanel.add(jLabel3, gridBagConstraints);

        maxLogRangeField.setText("100");
        maxLogRangeField.setMinimumSize(new java.awt.Dimension(60, 20));
        maxLogRangeField.setName("maxLogRangeField"); // NOI18N
        maxLogRangeField.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        logRangePanel.add(maxLogRangeField, gridBagConstraints);

        eqSpacedLogRangeToggle.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        eqSpacedLogRangeToggle.setText("equally spaced");
        eqSpacedLogRangeToggle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eqSpacedLogRangeToggle.setName("eqSpacedLogRangeToggle"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        logRangePanel.add(eqSpacedLogRangeToggle, gridBagConstraints);

        logValSlider.setMaximum(9);
        logValSlider.setValue(2);
        logValSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "values/decade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        logValSlider.setName("logValSlider"); // NOI18N
        logValSlider.setPreferredSize(new java.awt.Dimension(100, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        logRangePanel.add(logValSlider, gridBagConstraints);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.GridBagLayout());

        setLogRangeButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        setLogRangeButton.setText("set");
        setLogRangeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        setLogRangeButton.setName("setLogRangeButton"); // NOI18N
        setLogRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLogRangeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(setLogRangeButton, gridBagConstraints);

        addLogRangeButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addLogRangeButton.setText("add");
        addLogRangeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addLogRangeButton.setName("addLogRangeButton"); // NOI18N
        addLogRangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLogRangeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel8.add(addLogRangeButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        logRangePanel.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.6;
        add(logRangePanel, gridBagConstraints);

        arrayPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "values", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        arrayPanel.setName("arrayPanel"); // NOI18N
        arrayPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        thresholdList.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        thresholdList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "0", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        thresholdList.setAlignmentX(0.0F);
        thresholdList.setName("thresholdList"); // NOI18N
        jScrollPane1.setViewportView(thresholdList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        arrayPanel.add(jScrollPane1, gridBagConstraints);

        deleteSelButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        deleteSelButton.setText("delete");
        deleteSelButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        deleteSelButton.setName("deleteSelButton"); // NOI18N
        deleteSelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        arrayPanel.add(deleteSelButton, gridBagConstraints);

        clearThrButton.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        clearThrButton.setText("clear list");
        clearThrButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clearThrButton.setName("clearThrButton"); // NOI18N
        clearThrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearThrButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        arrayPanel.add(clearThrButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.4;
        add(arrayPanel, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void setLinRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLinRangeButtonActionPerformed
   try
   {
      thresholds = Range.createLinearRange(rmin, rmax, intervalCombo.getSelectedInterval());
      setThresholds();
   } catch (Exception e)
   {
   }
}//GEN-LAST:event_setLinRangeButtonActionPerformed

private void addLinRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLinRangeButtonActionPerformed
   try
   {
      mergeRange(Range.createLinearRange(rmin, rmax, intervalCombo.getSelectedInterval()));
      setThresholds();
   } catch (Exception e)
   {
   }
}//GEN-LAST:event_addLinRangeButtonActionPerformed

private void clearThrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearThrButtonActionPerformed
   float v = thrSlider.getVal();
   thresholds = new float[] {v};
   setThresholds();
}//GEN-LAST:event_clearThrButtonActionPerformed

private void setLogRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLogRangeButtonActionPerformed
   try
   {
       thresholds = Range.createLogRange(logValSlider.getValue(),
                                         Float.parseFloat(minLogRangeField.getText()),
                                         Float.parseFloat(maxLogRangeField.getText()),
                                         eqSpacedLogRangeToggle.isSelected());
        setThresholds();
   } catch (Exception e)
   {
   }
}//GEN-LAST:event_setLogRangeButtonActionPerformed

private void addLogRangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLogRangeButtonActionPerformed
   try
   {
   mergeRange(Range.createLogRange(logValSlider.getValue(),
                                   Float.parseFloat(minLogRangeField.getText()),
                                   Float.parseFloat(maxLogRangeField.getText()),
                                   eqSpacedLogRangeToggle.isSelected()));
   setThresholds();
   } catch (Exception e)
   {
   }
}//GEN-LAST:event_addLogRangeButtonActionPerformed

private void thrSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thrSliderStateChanged
   if (thrSlider.isAdjusting())
      return;
   if (thresholds == null || setThrButton.isSelected())
      thresholds = new float[]{thrSlider.getVal()};
   else
   {
      float[] oldThr = thresholds;
      int nThr = oldThr.length + 1;
      thresholds = new float[oldThr.length + 1];
      System.arraycopy(oldThr, 0, thresholds, 0, oldThr.length);
      thresholds[oldThr.length] = thrSlider.getVal();
   }
   setThresholds();
}//GEN-LAST:event_thrSliderStateChanged

private void deleteSelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelButtonActionPerformed
   if (thresholds == null)
      return;
   int[] toDel = thresholdList.getSelectedIndices();
   float[] tmpThr = new float[thresholds.length];
   int n = 0;
   for (int i = 0, k = 0; i < tmpThr.length; i++)
   {
      if (k < toDel.length && i == toDel[k])
         k += 1;
      else
      {
         tmpThr[n] = thresholds[i];
         n += 1;
      }
   }
   if (n == 0)
   {
      tmpThr[0] = thrSlider.getVal();
      n = 1;
   }
   thresholds = new float[n];
   System.arraycopy(tmpThr, 0, thresholds, 0, n);
   setThresholds();
}//GEN-LAST:event_deleteSelButtonActionPerformed

   private void minLinFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_minLinFieldActionPerformed
   {//GEN-HEADEREND:event_minLinFieldActionPerformed
      try
      {
         rmin = Float.parseFloat(minLinField.getText());
         intervalCombo.setRangeLength(rmax - rmin, maxRangeCount);
      } catch (Exception e)
      {
      }
   }//GEN-LAST:event_minLinFieldActionPerformed

   private void maxLinFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_maxLinFieldActionPerformed
   {//GEN-HEADEREND:event_maxLinFieldActionPerformed
      try
      {
         rmax = Float.parseFloat(maxLinField.getText());
         intervalCombo.setRangeLength(rmax - rmin, maxRangeCount);
      } catch (Exception e)
      {
      }
   }//GEN-LAST:event_maxLinFieldActionPerformed


   private void mergeRange(float[] range)
   {
      float[] oldThr = thresholds;
      int nThr = oldThr.length;
      if (range != null)
         nThr += range.length;
      thresholds = new float[nThr];
      System.arraycopy(oldThr, 0, thresholds, 0, oldThr.length);
      System.arraycopy(range, 0, thresholds, oldThr.length, range.length);
   }

   private void setThresholds()
   {
      float[] tmpThr = thresholds.clone();
      Arrays.sort(tmpThr);
      int nThr = 0;
      for (int i = 0; i < tmpThr.length; i++)
      {
         if (tmpThr[i] == tmpThr[nThr] && i > nThr || tmpThr[i] < physMin || tmpThr[i] > physMax)
            continue;
         tmpThr[nThr] = tmpThr[i];
         nThr += 1;
      }
      if (nThr == 0)
         return;
      thresholds = new float[nThr];
      System.arraycopy(tmpThr, 0, thresholds, 0, nThr);
      String format = "%." + (decimals + 2) + "f";
      String[] formattedThrs = new String[nThr];
      for (int i = 0; i < nThr; i++)
         formattedThrs[i] = String.format(format, thresholds[i]);
      thresholdList.setListData(formattedThrs);
      fireStateChanged();
   }

   public void setMinMax(float vMin, float vMax, float physMin, float physMax)
   {
      if (vMax < vMin + .00001f)
         vMax = vMin + .00001f;
      if (physMax < physMin + .00001f)
         physMax = physMin + .00001f;
      decimals = (int)(-Math.log10(vMax - vMin));
      if (decimals < 0) decimals = 0;
      decimals +=2;
      String format = "%."+decimals+"f";
      this.vMin = vMin;
      this.vMax = vMax;
      rmin = this.physMin = physMin;
      rmax = this.physMax = physMax;
      thrSlider.setMinMax(physMin, physMax);
      intervalCombo.setRangeLength(rmax - rmin, maxRangeCount);
      intervalCombo1.setRangeLength(rmax - rmin, maxRangeCount);
      minLinField.setText(String.format(format, physMin));
      maxLinField.setText(String.format(format, physMax));
      float lMax = max(abs(physMin), abs(physMax));
      if (physMin > 0)
         minLogRangeField.setText(String.format(format, physMin));
      else
         minLogRangeField.setText(String.format(format, lMax / 1000));
      maxLogRangeField.setText(String.format(format, lMax));
      if (startSingle) {
         thresholds = new float[]
         {
            (physMin + physMax) / 2
         };
         thrSlider.setVal(thresholds[0]);
      } else
      {
         try
         {
            thresholds = Range.createLinearRange(rmin, rmax, intervalCombo.getSelectedInterval());
         } catch (Exception e)
         {
         }
      }
      setThresholds();
   }

   public void setMaxRangeCount(int count)
   {
      maxRangeCount = 1 + (int)(Math.log10(Math.max(10., count)));
      intervalCombo.setRangeLength(rmax - rmin, maxRangeCount);
      intervalCombo1.setRangeLength(rmax - rmin, maxRangeCount);
   }

   public void setStartSingle(boolean startSingle)
   {
      this.startSingle = startSingle;
   }

   public float[] getThresholds()
   {
      if (thresholds == null)
         return null;
      float[] thr = new float[thresholds.length];
      for (int i = 0; i < thr.length; i++)
         thr[i] = vMin + (thresholds[i] - physMin) * (vMax - vMin) / (physMax - physMin);
      return thr;
   }
   /**
    * Utility field holding list of ChangeListeners.
    */
   private transient ArrayList<ChangeListener> changeListenerList =
           new ArrayList<ChangeListener>();

   /**
    * Registers ChangeListener to receive events.
    * @param listener The listener to register.
    */
   public synchronized void addChangeListener(ChangeListener listener)
   {
      changeListenerList.add(listener);
   }

   /**
    * Removes ChangeListener from the list of listeners.
    * @param listener The listener to remove.
    */
   public synchronized void removeChangeListener(ChangeListener listener)
   {
      changeListenerList.remove(listener);
   }

   /**
    * Notifies all registered listeners about the event.
    *
    * @param object Parameter #1 of the <CODE>ChangeEvent<CODE> constructor.
    */
   private void fireStateChanged()
   {
      ChangeEvent e = new ChangeEvent(this);
      for (ChangeListener listener : changeListenerList)
         listener.stateChanged(e);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLinRangeButton;
    private javax.swing.JButton addLogRangeButton;
    private javax.swing.JRadioButton addThrButton;
    private javax.swing.JPanel arrayPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearThrButton;
    private javax.swing.JButton deleteSelButton;
    private javax.swing.JCheckBox eqSpacedLogRangeToggle;
    private javax.swing.Box.Filler filler1;
    private pl.edu.icm.visnow.gui.widgets.IntervalCombo intervalCombo;
    private pl.edu.icm.visnow.gui.widgets.IntervalCombo intervalCombo1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linRangePanel;
    private javax.swing.JPanel logRangePanel;
    private javax.swing.JSlider logValSlider;
    private javax.swing.JTextField maxLinField;
    private javax.swing.JTextField maxLogRangeField;
    private javax.swing.JTextField minLinField;
    private javax.swing.JTextField minLogRangeField;
    private javax.swing.JButton setLinRangeButton;
    private javax.swing.JButton setLogRangeButton;
    private javax.swing.JRadioButton setThrButton;
    private javax.swing.JPanel simplePanel;
    private javax.swing.JPanel singleValPanel;
    private pl.edu.icm.visnow.gui.widgets.FloatSlider thrSlider;
    private javax.swing.JList thresholdList;
    // End of variables declaration//GEN-END:variables


    public static void main(String[] args) {
        JFrame f = new JFrame();
        final FloatArrayEditor p = new FloatArrayEditor();
        f.add(p);
        f.pack();
        f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        f.addComponentListener(new ComponentAdapter() {
            private boolean toggleSimple = true;
            @Override
            public void componentMoved(ComponentEvent e) {
                p.setPresentation(toggleSimple);
                toggleSimple = !toggleSimple;
            }
        });
        
        f.setVisible(true);
    }
}
