/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.lib.basic.mappers.InterpolatedSlice;

import pl.edu.icm.visnow.datasets.Field;
import pl.edu.icm.visnow.geometries.objects.SignalingTransform3D;
import pl.edu.icm.visnow.geometries.viewer3d.eventslisteners.pick.PickType;

public class GUI extends javax.swing.JPanel
{

   protected Params params;
   protected Field inField;

   /** Creates new form EmptyVisnowModuleGUI */
   public GUI()
   {
      initComponents();
      hoeKnifePickSwitchActionPerformed(null);
      hoeKnifePickSwitch.setVisible(false);
      use3DPickBtn.setVisible(false);
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      buttonGroup1 = new javax.swing.ButtonGroup();
      jPanel1 = new javax.swing.JPanel();
      use3DPickBtn = new javax.swing.JToggleButton();
      hoeKnifePickSwitch = new javax.swing.JToggleButton();
      transformPanel = new pl.edu.icm.visnow.geometries.gui.TransformPanel();
      jPanel2 = new javax.swing.JPanel();
      xButton = new javax.swing.JRadioButton();
      yButton = new javax.swing.JRadioButton();
      zButton = new javax.swing.JRadioButton();
      treeCreationLabel = new javax.swing.JLabel();
      iResolutionSlider = new pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider();
      jResolutionSlider = new pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider();

      setLayout(new java.awt.GridBagLayout());

      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/edu/icm/visnow/lib/basic/mappers/InterpolatedSlice/Bundle"); // NOI18N
      use3DPickBtn.setText(bundle.getString("GUI.use3DPickBtn.text")); // NOI18N
      use3DPickBtn.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            use3DPickBtnActionPerformed(evt);
         }
      });

      hoeKnifePickSwitch.setText(bundle.getString("GUI.hoeKnifePickSwitch.text")); // NOI18N
      hoeKnifePickSwitch.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            hoeKnifePickSwitchActionPerformed(evt);
         }
      });

      transformPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(transformPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(hoeKnifePickSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(use3DPickBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(hoeKnifePickSwitch)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(use3DPickBtn)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(transformPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29))
      );

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 6;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weighty = 1.0;
      add(jPanel1, gridBagConstraints);

      jPanel2.setLayout(new java.awt.GridLayout(1, 0));

      buttonGroup1.add(xButton);
      xButton.setText(bundle.getString("GUI.xButton.text")); // NOI18N
      xButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            xButtonActionPerformed(evt);
         }
      });
      jPanel2.add(xButton);

      buttonGroup1.add(yButton);
      yButton.setText(bundle.getString("GUI.yButton.text")); // NOI18N
      yButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            yButtonActionPerformed(evt);
         }
      });
      jPanel2.add(yButton);

      buttonGroup1.add(zButton);
      zButton.setSelected(true);
      zButton.setText(bundle.getString("GUI.zButton.text")); // NOI18N
      zButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            zButtonActionPerformed(evt);
         }
      });
      jPanel2.add(zButton);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      add(jPanel2, gridBagConstraints);

      treeCreationLabel.setText("cell tree not found");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      add(treeCreationLabel, gridBagConstraints);

      iResolutionSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("GUI.iResolutionSlider.border.title"))); // NOI18N
      iResolutionSlider.setMax(500);
      iResolutionSlider.setVal(100);
      iResolutionSlider.addChangeListener(new javax.swing.event.ChangeListener()
      {
         public void stateChanged(javax.swing.event.ChangeEvent evt)
         {
            iResolutionSliderStateChanged(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.weightx = 1.0;
      add(iResolutionSlider, gridBagConstraints);

      jResolutionSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("GUI.jResolutionSlider.border.title"))); // NOI18N
      jResolutionSlider.setMax(500);
      jResolutionSlider.setVal(100);
      jResolutionSlider.addChangeListener(new javax.swing.event.ChangeListener()
      {
         public void stateChanged(javax.swing.event.ChangeEvent evt)
         {
            jResolutionSliderStateChanged(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.gridwidth = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      add(jResolutionSlider, gridBagConstraints);
   }// </editor-fold>//GEN-END:initComponents

   private void setAxis()
   {
      if (xButton.isSelected())
         params.setAxis(0);
      if (yButton.isSelected())
         params.setAxis(1);
      if (zButton.isSelected())
         params.setAxis(2);
      resetTransform();
   }

   public void setInField(Field inField)
   {
      this.inField = inField;
      transformPanel.setTransSensitivity(inField.getDiameter()/1000);
   }

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_xButtonActionPerformed
    {//GEN-HEADEREND:event_xButtonActionPerformed
       setAxis();
    }//GEN-LAST:event_xButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yButtonActionPerformed
    {//GEN-HEADEREND:event_yButtonActionPerformed
       setAxis();
    }//GEN-LAST:event_yButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zButtonActionPerformed
    {//GEN-HEADEREND:event_zButtonActionPerformed
       setAxis();
    }//GEN-LAST:event_zButtonActionPerformed

   private void iResolutionSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_iResolutionSliderStateChanged
   {//GEN-HEADEREND:event_iResolutionSliderStateChanged
      if (!iResolutionSlider.isAdjusting())
         params.setResolution(new int[]{Math.max(10, iResolutionSlider.getVal()), 
                                        Math.max(10, jResolutionSlider.getVal())});
   }//GEN-LAST:event_iResolutionSliderStateChanged

   private void jResolutionSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jResolutionSliderStateChanged
   {//GEN-HEADEREND:event_jResolutionSliderStateChanged
      if (!jResolutionSlider.isAdjusting())
         params.setResolution(new int[]{Math.max(10, iResolutionSlider.getVal()), 
                                        Math.max(10, jResolutionSlider.getVal())});
   }//GEN-LAST:event_jResolutionSliderStateChanged

    private void use3DPickBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_use3DPickBtnActionPerformed
        params.getPick3DListener().setActive(use3DPickBtn.isSelected());
    }//GEN-LAST:event_use3DPickBtnActionPerformed

    private void hoeKnifePickSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoeKnifePickSwitchActionPerformed
        if (hoeKnifePickSwitch.isSelected()) {
            hoeKnifePickSwitch.setText("hoe pick");
            if (params != null && params.pick3DListener != null)
                params.pick3DListener.setPickType(PickType.PLAIN_HOE);
        } else {
            hoeKnifePickSwitch.setText("knife pick");
            if (params != null && params.pick3DListener != null)
               params.pick3DListener.setPickType(PickType.PLAIN_KNIFE);
        }
    }//GEN-LAST:event_hoeKnifePickSwitchActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JToggleButton hoeKnifePickSwitch;
   private pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider iResolutionSlider;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider jResolutionSlider;
   private pl.edu.icm.visnow.geometries.gui.TransformPanel transformPanel;
   private javax.swing.JLabel treeCreationLabel;
   private javax.swing.JToggleButton use3DPickBtn;
   private javax.swing.JRadioButton xButton;
   private javax.swing.JRadioButton yButton;
   private javax.swing.JRadioButton zButton;
   // End of variables declaration//GEN-END:variables

   /**
    * Set the value of params
    *
    * @param params new value of params
    */
   public void setParams(Params params)
   {
      this.params = params;
      transformPanel.setTransformParams(params.getTransform());
      use3DPickBtn.setSelected(params.getPick3DListener().isActive());
      hoeKnifePickSwitch.setSelected(params.getPick3DListener().getPickType() == PickType.PLAIN_HOE);
   }
   
   public void setSignalingTransform(SignalingTransform3D sigTrans)
   {
      transformPanel.setSigTrans(sigTrans);
   }

   public void resetTransform()
   {
      transformPanel.resetTransform();
   }

   public void creatingTreeInfo(boolean exec)
   {
      if (exec)
         treeCreationLabel.setText("Creating cell tree. Please wait.");
      else
         treeCreationLabel.setText("Cell tree created.");
   }
   
}
