/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.geometries.gui;

import pl.edu.icm.visnow.lib.gui.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import pl.edu.icm.visnow.datasets.Field;
import pl.edu.icm.visnow.datasets.IrregularField;
import pl.edu.icm.visnow.datasets.RegularField;
import pl.edu.icm.visnow.geometries.parameters.IrregularFieldDisplayParams;

/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class FieldMapperGUI extends javax.swing.JPanel implements ChangeFiringGUI
{
    protected RegularField regularInField = null;
    protected IrregularField irregularInField = null;
    protected Vector<CellSetPresentationGUI> cellSetPresentationGUIs = new Vector<CellSetPresentationGUI>();
    protected IrregularFieldDisplayParams irregularFieldDisplayParams = null;
    /** Creates new form FieldMapperGUI */
    public FieldMapperGUI()
    {
        initComponents();
        cellSetPresentationGUIs.add(new CellSetPresentationGUI());
        redisplay();
    }
    
   public void setInData(Field inField, IrregularFieldDisplayParams params)
   {
      CardLayout cl = (CardLayout) getLayout();
      cellSetPresentationGUIs.clear();
      if (inField instanceof IrregularField)
      {
         regularInField = null;
         irregularInField = (IrregularField)inField;
         for (int i = 0; i < irregularInField.getNCellSets(); i++)
         {
            CellSetPresentationGUI csGUI = new CellSetPresentationGUI(irregularInField.getCellSet(i), inField, params.getCellSetDisplayParameters(i));
            cellSetPresentationGUIs.add(csGUI);
         }
         redisplay();
         cl.show(this, "irregular");
      } else
      {
         irregularInField = null;
         regularInField = (RegularField) inField;
         regularFieldPresentationGUI.setInField(regularInField);
         cl.show(this, "regular");
      }
   }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      irregularFieldMapPanel = new javax.swing.JPanel();
      presentationPanel = new javax.swing.JPanel();
      pane = new javax.swing.JTabbedPane();
      jPanel5 = new javax.swing.JPanel();
      regularFieldPresentationGUI = new pl.edu.icm.visnow.geometries.gui.RegularFieldPresentationGUI();

      setMinimumSize(new java.awt.Dimension(180, 735));
      setPreferredSize(new java.awt.Dimension(200, 740));
      setLayout(new java.awt.CardLayout());

      irregularFieldMapPanel.setLayout(new java.awt.GridBagLayout());

      presentationPanel.setMinimumSize(new java.awt.Dimension(160, 470));
      presentationPanel.setPreferredSize(new java.awt.Dimension(200, 490));
      presentationPanel.setLayout(new java.awt.BorderLayout());
      presentationPanel.add(pane, java.awt.BorderLayout.CENTER);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      irregularFieldMapPanel.add(presentationPanel, gridBagConstraints);
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.weighty = 1.0;
      irregularFieldMapPanel.add(jPanel5, gridBagConstraints);

      add(irregularFieldMapPanel, "irregular");
      add(regularFieldPresentationGUI, "regular");
   }// </editor-fold>//GEN-END:initComponents

    private void redisplay()
    {
       pane.removeAll();
       for (CellSetPresentationGUI presentationGUI : cellSetPresentationGUIs)
          pane.add(presentationGUI, presentationGUI.getCellSetName());
    }

   public RegularFieldPresentationGUI getFieldPresentationGUI()
   {
      return regularFieldPresentationGUI;
   }

   public  RegularField3DMapPanel getRegularField3DMapPanel()
   {
      return regularFieldPresentationGUI.getRegularField3DMapPanel();
   }

   /**
    * Utility field holding list of ChangeListeners.
    */
   protected transient ArrayList<ChangeListener> changeListenerList = new ArrayList<ChangeListener>();

   /**
    * Registers ChangeListener to receive events.
    * @param listener The listener to register.
    */
   public synchronized void addChangeListener(ChangeListener listener)
   {
      changeListenerList.add(listener);
   }

   /**
    * Removes ChangeListener from the list of listeners.
    * @param listener The listener to remove.
    */
   public synchronized void removeChangeListener(ChangeListener listener)
   {
      changeListenerList.remove(listener);
   }

   public synchronized void clearChangeListeners()
   {
      changeListenerList.clear();
   }

    /**
    * Notifies all registered listeners about the event.
    *
    * @param object Parameter #1 of the <CODE>ChangeEvent<CODE> constructor.
    */
   public void fireStateChanged()
   {
      ChangeEvent e = new ChangeEvent(this);
      for (ChangeListener listener : changeListenerList)
         listener.stateChanged(e);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel irregularFieldMapPanel;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JTabbedPane pane;
   private javax.swing.JPanel presentationPanel;
   private pl.edu.icm.visnow.geometries.gui.RegularFieldPresentationGUI regularFieldPresentationGUI;
   // End of variables declaration//GEN-END:variables

}
