//<editor-fold defaultstate="collapsed" desc=" COPYRIGHT AND LICENSE ">
/* VisNow
 Copyright (C) 2006-2013 University of Warsaw, ICM

 This file is part of GNU Classpath.

 GNU Classpath is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 GNU Classpath is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with GNU Classpath; see the file COPYING.  If not, write to the
 University of Warsaw, Interdisciplinary Centre for Mathematical and
 Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland.

 Linking this library statically or dynamically with other modules is
 making a combined work based on this library.  Thus, the terms and
 conditions of the GNU General Public License cover the whole
 combination.

 As a special exception, the copyright holders of this library give you
 permission to link this library with independent modules to produce an
 executable, regardless of the license terms of these independent
 modules, and to copy and distribute the resulting executable under
 terms of your choice, provided that you also meet, for each linked
 independent module, the terms and conditions of the license of that
 module.  An independent module is a module which is not derived from
 or based on this library.  If you modify this library, you may extend
 this exception to your version of the library, but you are not
 obligated to do so.  If you do not wish to do so, delete this
 exception statement from your version.
 */
//</editor-fold>

package pl.edu.icm.visnow.lib.basic.filters.InterpolationToRegularField;

import pl.edu.icm.visnow.datasets.Field;

public class GUI extends javax.swing.JPanel
{
   protected Field inField;
   protected Params params;
   private int trueDim;
   private float extsum = 3;
   private float invDelta= 1;
   private float[][] ext;

   /** Creates new form EmptyVisnowModuleGUI */
   public GUI()
   {
      initComponents();
      transformPanel.exportButtonVisible(false);
   }

   public void setInField(Field inField)
   {
      params.setActive(false);
      this.inField = inField;
      trueDim = inField.getTrueDim();
      transformPanel.setVisible(trueDim == 3);
      transform2DPanel.setVisible(trueDim == 2);
      extsum = 0;
      ext = inField.getExtents();
      for (int i = 0; i < trueDim; i++)
         extsum += ext[1][i] - ext[0][i];
      invDelta = trueDim * resSlider.getVal()/extsum;
      int[] res = new int[trueDim];
      for (int i = 0; i < trueDim; i++)
         res[i] = Math.max(2, (int)(invDelta * (ext[1][i] - ext[0][i])));
      params.setResolution(res);
      transformPanel.setTransSensitivity(inField.getDiameter()/500);
      transform2DPanel.setTransSensitivity(inField.getDiameter()/500);
      params.setActive(true);         
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        resSlider = new pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider();
        jButton1 = new javax.swing.JButton();
        transformPanel = new pl.edu.icm.visnow.geometries.gui.TransformPanel();
        transform2DPanel = new pl.edu.icm.visnow.geometries.gui.Transform2DPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new java.awt.GridBagLayout());

        resSlider.setBorder(javax.swing.BorderFactory.createTitledBorder("resolution"));
        resSlider.setMax(500);
        resSlider.setMin(50);
        resSlider.setName(""); // NOI18N
        resSlider.setVal(100);
        resSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resSliderStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(resSlider, gridBagConstraints);

        jButton1.setText("Output interpolated field");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jButton1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(transformPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(transform2DPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weighty = 1.0;
        add(filler2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
       params.setOutput(true);
    }//GEN-LAST:event_jButton1ActionPerformed

private void resSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resSliderStateChanged
       if (resSlider.isAdjusting() || ext == null)
          return;
      extsum = 0;
      ext = inField.getExtents();
      for (int i = 0; i < trueDim; i++)
         extsum += ext[1][i] - ext[0][i];
      invDelta = trueDim * resSlider.getVal()/extsum;
      int[] res = new int[trueDim];
      for (int i = 0; i < trueDim; i++)
         res[i] = Math.max(2, (int)(invDelta * (ext[1][i] - ext[0][i])));
      params.setResolution(res);
}//GEN-LAST:event_resSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private pl.edu.icm.visnow.gui.widgets.EnhancedIntSlider resSlider;
    private pl.edu.icm.visnow.geometries.gui.Transform2DPanel transform2DPanel;
    private pl.edu.icm.visnow.geometries.gui.TransformPanel transformPanel;
    // End of variables declaration//GEN-END:variables

   /**
    * Set the value of params
    *
    * @param params new value of params
    */
   public void setParams(Params params)
   {
      this.params = params;
      transformPanel.setTransformParams(params.getTransform());
      transform2DPanel.setTransformParams(params.getTransform());
   }
   
   public void resetTransform()
   {
      transformPanel.resetTransform();
      transform2DPanel.resetTransform();
   }

}
