/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.gui.widgets;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author babor
 */
public class SearchField extends javax.swing.JPanel
{

   private String emptyText = "<search>";
   private Color emptyFgColor = new java.awt.Color(199, 199, 252);
   private boolean empty = true;
   private String searchString = null;

   /**
    * Creates new form SearchField
    */
   public SearchField()
   {
      initComponents();
      searchTF.setText(emptyText);
      searchLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/edu/icm/visnow/gui/icons/small/Zoom24.gif")));
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        searchTF = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.GridBagLayout());

        searchTF.setForeground(new java.awt.Color(199, 199, 252));
        searchTF.setName("searchTF"); // NOI18N
        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });
        searchTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTFFocusLost(evt);
            }
        });
        searchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTFKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(searchTF, gridBagConstraints);

        searchLabel.setBackground(new java.awt.Color(255, 255, 255));
        searchLabel.setName("searchLabel"); // NOI18N
        searchLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weighty = 1.0;
        add(searchLabel, gridBagConstraints);

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setForeground(new java.awt.Color(102, 102, 102));
        clearButton.setText("x");
        clearButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        clearButton.setMinimumSize(new java.awt.Dimension(20, 20));
        clearButton.setName("clearButton"); // NOI18N
        clearButton.setPreferredSize(new java.awt.Dimension(20, 20));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(clearButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
       searchTFChanged();
       fireStateChanged();
    }//GEN-LAST:event_searchTFActionPerformed

    private void searchTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTFFocusLost
       searchTFChanged();
    }//GEN-LAST:event_searchTFFocusLost

    private void searchLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMouseClicked
       if (evt.getButton() == MouseEvent.BUTTON1)
       {
          searchTFChanged();
          fireStateChanged();
       }
    }//GEN-LAST:event_searchLabelMouseClicked

    private void searchTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTFFocusGained
       if (searchTF.getText().equals(emptyText))
       {
          searchTF.setForeground(Color.black);
          searchTF.setText("");
       }
    }//GEN-LAST:event_searchTFFocusGained

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        this.setText(null);
        searchTFChanged();
        fireStateChanged();       
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTFKeyReleased
        int mods = evt.getModifiers();
        if((mods & InputEvent.CTRL_DOWN_MASK) == InputEvent.CTRL_DOWN_MASK)
            return;
        
        searchTFChanged();
        fireStateChanged();       
    }//GEN-LAST:event_searchTFKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTF;
    // End of variables declaration//GEN-END:variables

   /**
    * @return the emptyText
    */
   public String getEmptySearchFieldText()
   {
      return emptyText;
   }

   /**
    * @param emptyText the emptyText to set
    */
   public void setEmptySearchFieldText(String emptyText)
   {
      this.emptyText = emptyText;
      if (empty)
      {
         searchTF.setForeground(emptyFgColor);
         searchTF.setText(emptyText);
      }
   }

   public void setText(String text)
   {
      if (text == null || text.length() == 0 || text.equals(""))
      {
         if (searchTF.hasFocus())
         {
            //??
         } else
         {
            searchTF.setForeground(emptyFgColor);
            searchTF.setText(emptyText);
         }
         searchString = null;
         empty = true;
      } else
      {
         searchTF.setForeground(Color.black);
         searchTF.setText(text);
         searchString = text;
         empty = false;
      }
   }

   /**
    * @return the emptyFgColor
    */
   public Color getEmptySearchFieldForegroundColor()
   {
      return emptyFgColor;
   }

   /**
    * @param emptyFgColor the emptyFgColor to set
    */
   public void setEmptySearchFieldForegroundColor(Color emptyFgColor)
   {
      this.emptyFgColor = emptyFgColor;
   }

   private void searchTFChanged()
   {
      String newText = searchTF.getText();
      if (newText.equals(emptyText))
      {
         searchString = null;
         //} else if(newText == null || newText.length() == 0 || newText.equals("")) {
         //do nothing
      } else
      { // if(newText == null || newText.length() == 0 || newText == "") {
         this.setText(newText);
      }
   }
   /**
    * Utility field holding list of ActionListeners.
    */
   private transient ArrayList<ActionListener> actionListenerList;
   /**
    * Utility field holding list of ChangeListeners.
    */
   private transient ArrayList<ChangeListener> changeListenerList = new ArrayList<ChangeListener>();

   /**
    * Registers ChangeListener to receive events.
    *
    * @param listener The listener to register.
    */
   public synchronized void addChangeListener(ChangeListener listener)
   {
      changeListenerList.add(listener);
   }

   /**
    * Removes ChangeListener from the list of listeners.
    *
    * @param listener The listener to remove.
    */
   public synchronized void removeChangeListener(ChangeListener listener)
   {
      changeListenerList.remove(listener);
   }

   /**
    * Notifies all registered listeners about the event.
    *
    * @param object Parameter #1 of the <CODE>ChangeEvent<CODE> constructor.
    */
   private void fireStateChanged()
   {
      ChangeEvent e = new ChangeEvent(this);
      for (ChangeListener listener : changeListenerList)
      {
         listener.stateChanged(e);
      }
   }

   /**
    * @return the searchString
    */
   public String getSearchString()
   {
      return searchString;
   }
}
