/* VisNow
 Copyright (C) 2006-2013 University of Warsaw, ICM

 This file is part of GNU Classpath.

 GNU Classpath is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 GNU Classpath is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with GNU Classpath; see the file COPYING.  If not, write to the 
 University of Warsaw, Interdisciplinary Centre for Mathematical and 
 Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

 Linking this library statically or dynamically with other modules is
 making a combined work based on this library.  Thus, the terms and
 conditions of the GNU General Public License cover the whole
 combination.

 As a special exception, the copyright holders of this library give you
 permission to link this library with independent modules to produce an
 executable, regardless of the license terms of these independent
 modules, and to copy and distribute the resulting executable under
 terms of your choice, provided that you also meet, for each linked
 independent module, the terms and conditions of the license of that
 module.  An independent module is a module which is not derived from
 or based on this library.  If you modify this library, you may extend
 this exception to your version of the library, but you are not
 obligated to do so.  If you do not wish to do so, delete this
 exception statement from your version. */
package pl.edu.icm.visnow.lib.basic.testdata.TestLineMesh;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;
import org.apache.log4j.Logger;
import pl.edu.icm.visnow.system.main.VisNow;

/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class GUI extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(GUI.class);
    
    private Params params;

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    public void setParams(Params params) {

        this.params = params;
        LOGGER.info(" " + params.getNPoints());
        sizeSlider.setVal(params.getNPoints());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeSlider = new pl.edu.icm.visnow.gui.widgets.ExtendedSlider();

        setLayout(new java.awt.BorderLayout());

        sizeSlider.setScaleType(pl.edu.icm.visnow.gui.widgets.ExtendedSlider.ScaleType.LOGARITHMIC);
        sizeSlider.setAutoscrolls(true);
        sizeSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "mesh size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10))); // NOI18N
        sizeSlider.setMax(10000.0F);
        sizeSlider.setMaximumSize(new java.awt.Dimension(200, 42));
        sizeSlider.setMin(10.0F);
        sizeSlider.setMinimumSize(new java.awt.Dimension(200, 42));
        sizeSlider.setName("sizeSlider"); // NOI18N
        sizeSlider.setVal(300.0F);
        sizeSlider.setVerifyInputWhenFocusTarget(false);
        sizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSliderStateChanged(evt);
            }
        });
        add(sizeSlider, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

   private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_sizeSliderStateChanged
   {//GEN-HEADEREND:event_sizeSliderStateChanged
        params.setNPoints(sizeSlider.getVal());
   }//GEN-LAST:event_sizeSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.edu.icm.visnow.gui.widgets.ExtendedSlider sizeSlider;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        VisNow.initLogging(true);
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame f = new JFrame();
                f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
//                Params p = new Params();
                GUI g = new GUI();
//                g.setParams(p);
                f.add(g);
                f.pack();
                f.show();
            }
        });    
    }
}
