/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor;

import pl.edu.icm.visnow.geometries.viewer3d.Display3DPanel;

/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class DirectionalLightsEditorPanel extends javax.swing.JPanel
{
   private Display3DPanel panel = null;
   private DirectionalLightEditor[] editors;
   /** Creates new form DirectionalLightsEditorPanel */
   public DirectionalLightsEditorPanel()
   {
      initComponents();
      editors = new DirectionalLightEditor[] {directionalLightEditor1,
                                              directionalLightEditor2,
                                              directionalLightEditor3,
                                              directionalLightEditor4};
      for (int i = 0; i < editors.length; i++)
      {
         editors[i].setiEditor(i);
         editors[i].setParentPanel(this);
      }
   }

   public void setPanel(Display3DPanel panel)
   {
      this.panel = panel;
      for (int i = 0; i < editors.length; i++)
         editors[i].setLight(panel.getDirectionalLight(i));
   }
   
   public void changeDirectionEdit(int iEd, boolean edit)
   {
      for (int i = 0; i < editors.length; i++)
         if (i != iEd)
            editors[i].unsetDirectionEdit();
      if (edit)
         panel.moveDirectionalLight(iEd);
      else
         panel.moveScene();
   }
   
   public void releaseDirectionEdit()
   {
      for (int i = 0; i < editors.length; i++)
         editors[i].unsetDirectionEdit();
      panel.moveScene();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      directionalLightEditor1 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor();
      directionalLightEditor2 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor();
      directionalLightEditor3 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor();
      directionalLightEditor4 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor();

      setMinimumSize(new java.awt.Dimension(180, 111));
      setPreferredSize(new java.awt.Dimension(220, 111));
      setLayout(new java.awt.GridBagLayout());

      directionalLightEditor1.setName("directionalLightEditor1"); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
      add(directionalLightEditor1, gridBagConstraints);

      directionalLightEditor2.setName("directionalLightEditor2"); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 3);
      add(directionalLightEditor2, gridBagConstraints);

      directionalLightEditor3.setName("directionalLightEditor3"); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 3);
      add(directionalLightEditor3, gridBagConstraints);

      directionalLightEditor4.setName("directionalLightEditor4"); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 3);
      add(directionalLightEditor4, gridBagConstraints);
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor directionalLightEditor1;
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor directionalLightEditor2;
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor directionalLightEditor3;
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.DirectionalLightEditor directionalLightEditor4;
   // End of variables declaration//GEN-END:variables
}
