/* VisNow
   Copyright (C) 2006-2013 University of Warsaw, ICM

This file is part of GNU Classpath.

GNU Classpath is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

GNU Classpath is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Classpath; see the file COPYING.  If not, write to the 
University of Warsaw, Interdisciplinary Centre for Mathematical and 
Computational Modelling, Pawinskiego 5a, 02-106 Warsaw, Poland. 

Linking this library statically or dynamically with other modules is
making a combined work based on this library.  Thus, the terms and
conditions of the GNU General Public License cover the whole
combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent
modules, and to copy and distribute the resulting executable under
terms of your choice, provided that you also meet, for each linked
independent module, the terms and conditions of the license of that
module.  An independent module is a module which is not derived from
or based on this library.  If you modify this library, you may extend
this exception to your version of the library, but you are not
obligated to do so.  If you do not wish to do so, delete this
exception statement from your version. */

package pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor;

import pl.edu.icm.visnow.geometries.viewer3d.Display3DPanel;

/**
 *
 ** @author Krzysztof S. Nowinski, University of Warsaw ICM
 */
public class PointLightsEditorPanel extends javax.swing.JPanel
{
   private Display3DPanel panel = null;
   private PointLightEditor[] editors;
   /** Creates new form PointLightsEditorPanel */
   public PointLightsEditorPanel()
   {
      initComponents();
      editors = new PointLightEditor[] {pointLightEditor1,pointLightEditor2,pointLightEditor3};
      for (int i = 0; i < editors.length; i++)
      {
         editors[i].setiEditor(i);
         editors[i].setParentPanel(this);
      }
   }

   public void setPanel(Display3DPanel panel)
   {
      this.panel = panel;
      for (int i = 0; i < editors.length; i++)
         editors[i].setLight(panel.getPointLight(i));
   }
   
   public void changePositionEdit(int iEd, boolean edit)
   {
      for (int i = 0; i < editors.length; i++)
         if (i != iEd)
            editors[i].unsetPositionEdit();
      if (edit)
         panel.movePointLight(iEd);
      else
         panel.moveObject();
   }
   
   public void releasePositionEdit()
   {
      for (int i = 0; i < editors.length; i++)
         editors[i].unsetPositionEdit();
      panel.moveObject();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      pointLightEditor1 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor();
      pointLightEditor2 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor();
      pointLightEditor3 = new pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor();

      setMinimumSize(new java.awt.Dimension(180, 90));
      setPreferredSize(new java.awt.Dimension(220, 90));
      setLayout(new java.awt.GridLayout(3, 0));

      pointLightEditor1.setName("pointLightEditor1"); // NOI18N
      add(pointLightEditor1);

      pointLightEditor2.setName("pointLightEditor2"); // NOI18N
      add(pointLightEditor2);

      pointLightEditor3.setName("pointLightEditor3"); // NOI18N
      add(pointLightEditor3);
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor pointLightEditor1;
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor pointLightEditor2;
   protected pl.edu.icm.visnow.geometries.viewer3d.controls.light_editor.PointLightEditor pointLightEditor3;
   // End of variables declaration//GEN-END:variables
}
